name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  darwin:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Test
        run: make tests
